{
 "title": "Lenovo Ideapad Health",
 "description": "name change",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utlization (%)",
   "type": "timeseries",
   "description": "Calculated as (100 - idle CPU).",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (min(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilzation (%) - RAM",
   "type": "timeseries",
   "description": "Calculated as %age of free memory bytes.",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n/\nnode_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM ( / 7.66 Gb )",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "UsedMemory"
    }
   ]
  },
  { "title": "Disk Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disk Utilzation (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\"})\n/ node_filesystem_size_bytes{fstype!=\"tmpfs\"} * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization ( Root FS )",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"/\"}/1024 \n- node_filesystem_avail_bytes{mountpoint=~\"/\"}/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=~\"/\"}/1024",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Utilization ( Boot/EFI FS )",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"/boot/efi\"}/1024 \n- node_filesystem_avail_bytes{mountpoint=~\"/boot/efi\"}/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=~\"/boot/efi\"}/1024",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Utilization ( Boot FS )",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~\"/boot\"}/1024 \n- node_filesystem_avail_bytes{mountpoint=~\"/boot\"}/1024",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=~\"/boot\"}/1024",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Filesystem Mountpoints",
   "type": "table",
   "description": "To make sure no new FS are present",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mountpoint)(node_filesystem_size_bytes{fstype!=\"tmpfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Temperature ( All Cores ) ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (chip)(node_hwmon_temp_celsius)",
     "legendFormat": "{{chip}}"
    }
   ]
  }
 ]
}